version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:blub
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:blub
    build:
      context:  ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    image: nginx:blub
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/blub/data/wordpress
      o: bind
      type: none
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/blub/data/mariadb
      o: bind
      type: none
