version: '3.8'

services:
  nginx:
    build: 
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/tools/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./requirements/mariadb/temp:/var/lib/mysql

  wordpress:
    build:
      context:  ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated

  wp:
    build:
      context: ./requirements/wp/
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
    entrypoint: ['wp', '--allow-root']


#services:
#  mariadb:
#    build: requirements/mariadb/
#    container_name: mariadb
#    volumes:
#      - mariadb:/var/lib/mysql
#    env_file:
#      - .env
#    networks:
#      - inception
#    restart: always
#
#  wordpress:
#    build: requirements/wordpress/
#    container_name: wordpress
#    depends_on:
#      - mariadb
#    env_file:
#      - .env
#    expose:
#      - 9000
#    networks:
#      - inception
#    volumes:
#      - wordpress:/var/www/html
#    restart: always
#
#  nginx:
#    build: requirements/nginx/
#    container_name: nginx
#    depends_on:
#      - wordpress
#    ports:
#      - "443:443"
#    networks:
#      - inception
#    volumes:
#      - wordpress:/var/www/html
#    restart: always
#
#volumes:
#  wordpress:
#    name: wordpress
#    driver: local
#    driver_opts:
#      device: /home/blub/inception/srcs/wordpress
#      o: bind
#      type: none
#  
#  mariadb:
#    name: mariadb
#    driver: local
#    driver_opts:
#      device: /home/blub/inception/srcs/mariadb
#      o: bind
#      type: none
#networks:
#  inception:
#    name: inception