# after the Debian i maybe still need to specify the right version
FROM Debian:latest

# -y is there to automatily answers questions with yes
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y mariadb-server
