version: '3.8'

services:

  nginx:
    build: nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

  wordpress:
    build: wordpress/
    container_name: wordpress
#    depends_on:
#      - mariadb
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

#  mariadb:
#    build: src/mariadb
#    container_name: mariadb
#    networks:
#      - inception
#    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/blub/inception/srcs/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception
